Fetch countries from the API and display them with their details
Zel-hub7/countries pull request #5
Opened 2023-09-06 08:40 UTC by Zel-hub7

1. I used an aredux store and reducers for my API.
2. I fetched all the countries from the API to the page and added a router to it that has the details.
3. I added search and sorting functionalities.
4. I tried to keep the basic structure of the design given in the requirement.

2023-09-06 14:26 UTC, omar-muhamad requested changes
# Changes Required ♻️
### Hi @Zel-hub7,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [ ] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-06 14:26 UTC, omar-muhamad commented on README.md
> +
- [ ] [Optional] Good job that you pay appreciation for the original designer here in the `Acknowledgments` section, but it would be much better if you added links for her Behance profile and the design link also like that:

I give credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)).

2023-09-06 14:26 UTC, omar-muhamad commented on src/components/HomePage.css
> +}
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=You%20should%20follow%20these%20design%20guidelines%2C%20including%3A), Please make the list of countries two columns only to match the given design because it's required to maintain the same page layout.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/Zel-hub7/countries/assets/68796232/2469db10-d22c-47bf-ae2e-8b5693a088b6) | ![image](https://github.com/Zel-hub7/countries/assets/68796232/dd881d28-0c71-4675-8671-97e5779e8473)  |

2023-09-06 14:26 UTC, Omar-Muhamad commented on src/index.css
> +    'Courier New',
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=You%20should%20follow%20these%20design%20guidelines%2C%20including%3A), Please stick to the fonts on the given design `gill sans` as body and title font and `lato` as control font. Kindly give every element of the two pages you have the correct font family.

![image](https://github.com/Zel-hub7/countries/assets/68796232/adcd7e8d-38a3-438a-992d-4d7034cfa122)

2023-09-06 14:26 UTC, omar-muhamad commented on src/components/details.js
>            onClick={() => navigation(-1)}
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=You%20should%20follow%20these%20design%20guidelines%2C%20including%3A), Please place the back navigation button on the top left of the navigation bar of the details page to match the given design.
- [ ] Please add the correct width and margin values for the details inside the `country details` page to match the given design because this is a mobile app so the the design is supposed to be suitable for the mobile view.


| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/Zel-hub7/countries/assets/68796232/574492b3-228a-4275-a79c-9b3fa10cf228) | ![image](https://github.com/Zel-hub7/countries/assets/68796232/5085392e-1e25-46f1-93f3-80ae38c375b0) |

2023-09-06 14:26 UTC, Omar-Muhamad commented on src/tests/navBar.test.js
> +});
- [ ] You only added a screenshot test for the navbar component, As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=the%20home%20page.-,Testing%20requirements,-Create%20unit%20tests), please add unit tests for several components of the app and some pure functions in Redux code and integration tests using React Testing Library by mocking data fetching and Redux Store connection.

2023-09-07 15:21 UTC, Gambit142 approved these changes
Hi @Zel-hub7 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Setup linters correctly ✔️ 
- Application has two pages ✔️ 
- Use of _**redux**_ for store management ✔️

### Optional Suggestion

- Kindly consider all the comments tagged [OPTIONAL] under this review summary. I strongly recommend that you implement them because they will make your application function better. 👍 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 15:21 UTC, Gambit142 commented on src/components/details.css
> +
- [OPTIONAL] I would advise you to reduce the font for the header so that your design looks good all the time even if the name of the country is composed of many characters. 👍 😎

### Hint: You can add these style declarations:

```CSS
    font-size: 1.5rem;
    align-self: center;
```

2023-09-07 15:21 UTC, Gambit142 commented on src/components/NavBar.css
> +
- [OPTIONAL] I would advise that you use `display: flex` to align the two icons in this div. This will ensure that they remain on the same row. Besides, using _**Flexbox**_ makes your design responsive. 👍 😎 

#### Hint: You can use these style declarations:

```css
    display: flex;
    align-self: center;
```

2023-09-07 15:21 UTC, Gambit142 commented on src/components/details.css
> +
- [OPTIONAL] Kindly remove all commented-out codes from your CSS file. Removing unused codes makes your code look clean and readable. 💻 🖱️

2023-09-07 18:39 UTC, merged